### ISSUE TITLE
Images are huge

### ISSUE THREAD

**Issue by charmeleon-zz** [hhester21/Way-to-go#7]
Please see https://engineeringblog.yelp.com/2017/06/making-photos-smaller.html for reducing image sizes without quality loss.

You don't need to do this via a node package, you can do it with creative studio http://help.adobe.com/en_US/creativesuite/cs/using/WS6E857477-27FE-4a88-B8A4-074DC3C65F68.html#WSB3484C68-ECD2-4fa4-B7CC-447A5FE86680, https://tinyjpg.com/, I've even had people do it with Microsoft paint. Huge images are a burden and make for a painful user experience (even checking out this repo took too long)

ping @kimjaydot

**Comment by kimjaydot** [comment]
I will check this during class, my repo is behind others. I thought I did optimize images for web, but I will do again.
